### ISSUE TITLE
Render more POIs

### ISSUE THREAD

**Issue by sethfitz** [AmericanRedCross/posm-carto#14]
POIs are gathered as part of the OMK workflow, so being able to see if they already exist is useful. It's also nice to be able to show what's been accomplished.

@hallahan is there a common list of POIs that are typically captured?

**Comment by hallahan** [comment]
If possible, I'd try and catch all nodes with tags.

OpenMapKit Android currently will make a marker for any node with tags. The internal OSM downloader is smart and does just that. `osmosis` isn't quite as flexible as Overpass, so I actually give it a list of things to consider when cutting a POI OSM file. I think this list is satisfactory.

https://github.com/AmericanRedCross/posm-admin/blob/master/scripts/omk-osm.sh#L29

Can you just have mapnik catch all nodes with tags? 80% of the time, just catching a name tag does the trick.

**Comment by almccon** [comment]
I've got some things enabled now, anything that is a point feature that's got a name, and most of them match up with Maki icons. Still a bit more to do: anything that corresponds with Maki but _doesn't_ have a name should show up, as well as Maki icons for area features with the same tags.

![screen shot 2016-04-21 at 21 apr 6 50 34](https://cloud.githubusercontent.com/assets/1212178/14729376/203114cc-07f2-11e6-8a48-36b695c53d6e.png)

**Comment by almccon** [comment]
904a0d35e740c91cea576a7fcd88232233dd47c0 added many more POIs. Re-open or create new issues for any specific ones that are missing.

I decided not to just label all nodes with tags, since some of those are labeled (or consciously not labeled at certain zooms, like nodes for country names, etc) in other parts of the stylesheet, so it would've taken a bit more logic to control for those.
