### ISSUE TITLE
Make roads wider at high zooms

### ISSUE THREAD

**Issue by sethfitz** [AmericanRedCross/posm-carto#7]
Particularly noticeable at z21, but likely useful to make them wider at lower zooms.

The specific experience that we had with road widths was that volunteers would annotate the printed maps with arrows indicating that buildings should be moved closer to the road, since it was probably the equivalent of a foot or so wide.

**Comment by almccon** [comment]
From @aawiseman:
![](https://cloud.githubusercontent.com/assets/5025092/14367500/64cbe1c8-fce6-11e5-9472-7f6f58a26b62.png)

![](https://cloud.githubusercontent.com/assets/5025092/14367501/64ce4cc4-fce6-11e5-825f-5e3322b51cbc.png)

**Comment by aawiseman** [comment]
Word up

**Comment by almccon** [comment]
So I did something that I've always wanted to try: from zoom 18 onward (up to 22) I double with z18 widths of the roads. So whatever the _real world_ width of the lines that are drawn at zoom 18 are the same real world widths in the deeper zooms. 

Of course, we don't actually _know_ the widths of any of these roads, and surely a `highway=residential` in one part of the world may be much narrower in the real world than the same class of feature in some other part of the world. So I was fairly conservative with the effective real world dimensions I chose. So, for `highway=residential` the width is 7 pixels at z18, which works out to about 4 meters wide. (At z18 at the equator, one pixel is about 0.6 m)

z18:
![screen shot 2016-04-21 at 21 apr 4 46 21](https://cloud.githubusercontent.com/assets/1212178/14727521/9d4c8566-07e0-11e6-9770-3450c81d9563.png)
z19:
![screen shot 2016-04-21 at 21 apr 4 46 39](https://cloud.githubusercontent.com/assets/1212178/14727526/a7d0b0f2-07e0-11e6-9881-24e765c7b0b1.png)
z20:
![screen shot 2016-04-21 at 21 apr 4 46 59](https://cloud.githubusercontent.com/assets/1212178/14727529/b28a2f50-07e0-11e6-8abc-c8321ebb6e26.png)
etc...

There are some cases where buildings overlap the roads (which is inevitable for urban areas that might have very narrow roads that are legitimately tagged as residential) but in the very worst cases, I think this is because the building data is wrong. So I added a semi-transparent building layer on top of the roads (in addition to the full opacity buildings that are under the roads layer). Hopefully this helps with QAing the building data.

For example, this spot which has a lot of building overlap, looks from the satellite layer that the problem is with the buildings, not the roads.

![screen shot 2016-04-21 at 21 apr 4 49 33](https://cloud.githubusercontent.com/assets/1212178/14727576/3283133e-07e1-11e6-8835-04809ec51933.png)
![screen shot 2016-04-21 at 21 apr 4 50 06](https://cloud.githubusercontent.com/assets/1212178/14727578/37b495f8-07e1-11e6-9709-8fbf4e8e4736.png)
http://www.openstreetmap.org/edit#map=20/-3.48342/-80.24375

Thoughts, @aawiseman @dalekunce?

**Comment by dalekunce** [comment]
@almccon that looks awesome.

road width feature will be highly useful.

**Comment by almccon** [comment]
Ok, I'm going to merge it in to master so it's easier for you all to test. Let me know how it goes!

**Comment by almccon** [comment]
![full width zoom](https://cloud.githubusercontent.com/assets/1212178/14729391/369a32fc-07f2-11e6-980e-b591db652ea0.gif)
